apiVersion: v1
kind: Service
metadata:
  name: zubi-python-service
spec:
  selector:
    app: python-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
